import Modal from './Components/Modals/Modal';
import RegisterModal from './Components/Modals/RegisterModal';
import  Navbar  from './Components/Navbar/Navbar'
import './globals.css'
import { Nunito } from 'next/font/google'

export const metadata = {
  title: 'Airbnb',
  description: 'Generated by create next app',
}
const font = Nunito({ 
  subsets: ['latin'], 
});
export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
      <RegisterModal/>
      <Navbar/>
        {children}</body>
    </html>
  )
}
